name: NPM publish

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: git config --global user.name "GitHub CD bot"
      - run: git config --global user.email "github-cd-bot@it-minds.dk"
      - run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}
      - run: npm run build
      - run: cp LICENSE build/LICENSE
      - run: cp package.json build/package.json
      - run: cp README.md build/README.md
      - run: cp .npmignore build/.npmignore
      - run: cd build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      # - run: git push
      #   env:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
